spring.application.name=service-registry

# Eureka Server Properties
eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

# Eureka Server Default Port
server.port=8761

